### ISSUE TITLE
Autocomplete malfunctions when this plugin is enabled.

### ISSUE THREAD

**Issue by kingsimba** [fingeg/DoxygenComments#1]
version: 1.0.4

## Problem Description
When I choose an item(i) from the auto-complete list, the next item(i+1) will be used.

For example, if I choose ``addListener``, ``alloc`` will be used instead.

![image](https://user-images.githubusercontent.com/8407634/83109772-8e6a0a80-a0f4-11ea-8363-0baa456ed824.png)

If I disable this plugin, the problem disappears.

**Comment by ghost** [comment]
Same here, but for me it only does this while trying to do autocomplete with Tab. Autocompleting by pressing space still behave as expected.

**Comment by fingeg** [comment]
Fixed in version 1.0.5
