### ISSUE TITLE
Visual Studio 2019 hangs

### ISSUE THREAD

**Issue by fallenworld1** [fingeg/DoxygenComments#15]
Hi,

steps to reproduce:
1. create empty project
2. put a break point or debug with initial break(f11 i belive)
3. start typing new variable in watch window like: `int *`

![image](https://user-images.githubusercontent.com/13927471/131515318-72922df8-a4a5-4881-bbd8-11f4c477a914.png)

this will hang visual studio

**Comment by fingeg** [comment]
Thanks for the issue. Fixed in version 2.0.2.
Just published it
