### ISSUE TITLE
C++ new line brace positioning is affected

### ISSUE THREAD

**Issue by Iizuki** [fingeg/DoxygenComments#3]
Normally when I type:
```
if (a > b){}  //the closing brace is inserted automatically
```  
and hit enter, I end up with this:
```
if (a > b) {    
    //the caret is here     
}
```

With this extension enabled I end up with this:
```
if (a > b) {  
} //the caret is before the closing brace
```

The same thing probably happens with functions etc. also.

Settings at _Tools > Options > Text Editor > C/C++ > Formatting > New Lines_ don't seem to have much effect.

**Comment by a-lerion** [comment]
I guess VS behaviour is also to blame here, perhaps even more so.
If you move the carret and move it back (this is actually done by the extension)  VS won't format the block after pressing enter.
