### ISSUE TITLE
Support older Visual Studio Versions

### ISSUE THREAD

**Issue by sangkmt** [fingeg/DoxygenComments#7]
Can you update for VS older such as VS 2017

**Comment by fingeg** [comment]
There already is a [plugin](https://marketplace.visualstudio.com/items?itemName=dragospop.CppDoxyComplete) for older versions (2013, 2015, 2017). 
It does not have as much features, but it should work, too.

Does that work for you?

**Comment by sangkmt** [comment]
Sorry, but this plugin version has no format needed such as:
//! @fn
//! @brief
//! @param[in]
//! @param[out]
//! @return
//! @date

Is there any way to change the default comment format of this plugin?

Vào 14:41, Th 4, 20 thg 1, 2021 Finn <notifications@github.com> đã viết:

**Comment by fingeg** [comment]
> Is there any way to change the default comment format of this plugin? 

In [that plugin](https://marketplace.visualstudio.com/items?itemName=dragospop.CppDoxyComplete) there is no option to customize the comments.

I am sorry, but I don't think I have the time to migrate the package to older versions right now, 
but if you want to contribute and create a pull request, I will be happy to review and test the results.

I will let this issue open, maybe someday there will be time for this.

**Comment by sangkmt** [comment]
Thanks, I am considering doing this later this week.  If okay I will send
you to rate it.

Vào 15:58, Th 4, 20 thg 1, 2021 Finn <notifications@github.com> đã viết:

**Comment by qing666888** [comment]
Please update the old version support such as VS 2017。CppDoxyComplete  Unable to customize format

**Comment by fingeg** [comment]
Added support in version 2.0.0
