### ISSUE TITLE
Excess slash when using triple slash style comments.

### ISSUE THREAD

**Issue by jjELT** [fingeg/DoxygenComments#8]
When changing the template in `Options > Doxygen > Function` to
```
/// @brief $BRIEF$END.
///
/// @param $PARAMS
/// @return $RETURN
```
in order to use the triple slash style `///` instead of the JavaDoc style `/** */` for doxygen comments, there is an excess slash added to the first line, like so:

```
//// @brief My function name.
///
/// @param var1
/// @param var2
/// @param var3
/// @param var4
/// @return
```

**Comment by fingeg** [comment]
Thanks for your feedback.
Fixed in version 1.1.5
